;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Data.Damage.BonusDamage",DevComment="")
+GameplayTagList=(Tag="Data.Damage.BonusStunDamage",DevComment="")
+GameplayTagList=(Tag="Data.Stun.DrainRate",DevComment="")
+GameplayTagList=(Tag="Data.Stun.Duration",DevComment="")
+GameplayTagList=(Tag="Effect.Combat.DamageMultiplier",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Attack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Attack.Melee.HeavyCounterAttack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Attack.Melee.LightAttack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Attack.Melee.LightCounterAttack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Block",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Dead",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Dodge",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Hurt",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Move",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Stun",DevComment="")
+GameplayTagList=(Tag="GameplayEvent.TargetAttacked",DevComment="")
+GameplayTagList=(Tag="State.Attack",DevComment="")
+GameplayTagList=(Tag="State.Block",DevComment="")
+GameplayTagList=(Tag="State.CanBeCountered",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="State.Dodge",DevComment="")
+GameplayTagList=(Tag="State.Dodge.PerfectDodge",DevComment="")
+GameplayTagList=(Tag="State.Hurt",DevComment="")
+GameplayTagList=(Tag="State.Move",DevComment="")
+GameplayTagList=(Tag="State.Stun",DevComment="")

