;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="GameplayAbility.Attack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Block",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Dodge",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Move",DevComment="")
+GameplayTagList=(Tag="State.Attack",DevComment="")
+GameplayTagList=(Tag="State.Block",DevComment="")
+GameplayTagList=(Tag="State.Dodge",DevComment="")
+GameplayTagList=(Tag="State.Move",DevComment="")

